# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/tutorial<%= ( ! ENV['GH_PREFIX'].nil? && ENV['GH_PREFIX'].empty? ) ? "" : "/#{ENV['GH_PREFIX']}"  %>"
url: "http://aizu-vim.github.io/tutorial"

# Build settings
gems: [jekyll-sass]
markdown: kramdown
permalink: pretty

exclude: [Gemfile, Gemfile.lock, README.md]

